### ISSUE TITLE
Fix Linting Issues

### ISSUE THREAD

**Issue by shubhamkorde** [AUV-IITK/Website2020#5]
The current state of the repository is highly linted. As we go along, our goal is to make the repository lint free. In order to solve this issue follow the given steps.

1. To understand what is meant by linting checkout [this](https://www.perforce.com/blog/qac/what-lint-code-and-why-linting-important#:~:text=Linting%20is%20the%20automated%20checking,a%20Unix%20utility%20for%20C.) document.
2. Install ESlint and enable extension in your code editor. Checkout this [wiki](https://github.com/AUV-IITK/Website2020/wiki/Installing-ESLint) page for the steps.
3. Comment on this issue to get assigned a particular folder to work on. Do not start working unless you have been assigned.
4. Once assigned, checkout all the files in that particular folder. In a given file the lint issues appear as red squiggly lines. On hovering them, a message is displayed stating the reason for the linting issue. 
5. Fix all the issues in the assigned folder. Checkout [this](https://github.com/AUV-IITK/Website2020/commit/cdff09e72e13c6b468cea95a3c9ee433d77d9f4f) commit for sample. Make sure that all the files in the particular folder are covered. 
6. Send a PR and respond to comments.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------

The folders that we need to update are;
- [ ] src/views/AboutUsPage @abhishekshree 
- [ ] src/views/BlogsPage @abhishekshree 
- [ ] src/views/ContactUsPage @abhishekshree
- [ ] src/views/EventsPage @abhishekshree
- [ ] src/views/LandingPage @abhishekshree
- [ ] src/views/SingleBlogs @Vedantttgitteee20 
- [ ] src/views/TeamPage
- [ ] src/views/Vehicles
- [ ] src/components/Footers @ritam2358 
- [ ] src/components/Navbars @ritam2358 
- [ ] src/components/UI @ritam2358

**Comment by shubhamkorde** [comment]
@ritam2358 Go ahead!

**Comment by abhishekshree** [comment]
I want to work on the first four pages, i.e. AboutUsPage, BlogsPage, ContactUsPage and EventsPage @shubhamkorde

**Comment by Vedantttgitteee20** [comment]
A request to work on folder src/views/SingleBlogs
